### ISSUE TITLE
Label providing incorrect 'for' attribute

### ISSUE THREAD

**Issue by dombarnes** [glyph-fr/simple_form_extension#12]
I have a form thats using the datetime extension to give me a date picker. I'm also using Rspec/Formulaic for testing, and its failing on these fields, that it can't find the field for the date attribute. I think the issue is in the label its creating:

A standard input of:
`<%= f.input :live_date %>`
and Rspec errors that it can't find the field, and my form shows:
`<label class="datetime required" for="webinar_live_date_1i">Live date <abbr title="required"></abbr></label>`

Just to test this on a normal text field:
With SFE enforcing a datetime type:

```
<label class="datetime required" for="webinar_title_1i">Title <abbr title="required"></abbr></label>
```

Whereas a normal text field has this:

```
<label class="string required" for="webinar_title">Title <abbr title="required"></abbr></label>
```

So I'm getting '_1i' appended to the end of the for attribute which I think may be causing the issues. It only seems to be SFE fields where I get this.

**Comment by dombarnes** [comment]
Did some more reading on this and I get the _1i prefix now.
In the end I redid my spec to run
````fill_in('model_date', with: attributes[:date])````
with Formulaic/Rspec to complete my field for the test.

 Not sure if this counts as a bug now as I guess maybe that is the right field attribute, perhaps some rspec helper is need to help with this?

**Comment by vala** [comment]
Hi @dombarnes can you provide me the following informations :

* Your `Webinar` model schema (Copy paste from `schema.rb`)
* The complete generated HTML for the input, including the wrapping `<div class="datetime">`

Does the date picker displays correctly when printed on a classic webpage ?

**Comment by dombarnes** [comment]
Schema.rb
````
create_table "webinars", force: :cascade do |t|
    t.datetime "live_date",                    null: false
    t.string   "title",                        null: false
    t.text     "description"
    t.integer  "presenter_id"
    t.string   "webinar_url"
    t.boolean  "active",       default: false
    t.datetime "created_at",                   null: false
    t.datetime "updated_at",                   null: false
  end
````

HTML
````
<div class="input datetime required webinar_live_date multiple-select-wrapper">
<label class="datetime required" for="webinar_live_date_1i">Live date <abbr title="required"></abbr>
</label>
<div class="input-group">
<input class="datetime required form-control" data-format="d/m/Y H:i" data-week-start-day="0" data-format-date="d/m/Y" type="text" name="webinar[live_date]" id="webinar_live_date">
<span class="input-group-ban">
<button type="button" class="btn btn-default datetimepicker-trigger"><i class="fa fa-calendar"></i></button>
</span>
</div>
</div>
````

Date picker appears fine and works as expected.

**Comment by vala** [comment]
OK so the label `for` attribute generation is the issue. I never dug into simple form's method to generate them, but the `_1i` suffix looks like simple form's original generated date input id.

Since your tests now pass, I'll try to check that when I have some time, and leave the issue open until then.

**Comment by vala** [comment]
Never checked it, and since it was almost 5 years ago I'll close it. Please reopen the issue if you're still interested in the fix
