### ISSUE TITLE
Does not work with Mongoid

### ISSUE THREAD

**Issue by ZiNTeR** [glyph-fr/simple_form_extension#14]
Hi, I'm trying to use it with my mongoid application. When in form i'm trying to do this:

`<%= f.input :fact_city, :as => :selectize, collection: City.all %>
`
I receive an error:

> uninitialized constant SimpleFormExtension::Inputs::SelectizeInput::ActiveRecord

But when i create my application, it was with --skip-active-records because of mongoid usage. Sorry for my English :)

**Comment by vala** [comment]
Hi @ZiNTeR, for now we didn't planned to support other ORMs than ActiveRecord, since we don't use them. But PRs are welcome to add support for Mongoid !
