### ISSUE TITLE
Simple_form_extension is breaking simple_form

### ISSUE THREAD

**Issue by schinsue** [glyph-fr/simple_form_extension#15]
`input :csv, as: :file ` turns into undefined method `csv?'

**Comment by vala** [comment]
file input is only compatible with `paperclip`. If you're using paperclip, ensure you defined `has_attached_file :csv`. If you're not, this is actually not supported, but PRs are always welcome for other libraries support

**Comment by schinsue** [comment]
@vala What if i don't wanna use the file input of simple_form_extension, but the one from simple_form?

**Comment by vala** [comment]
There is no way to do so for now, as for #7. This is a pending issue that we should fix quickly

**Comment by schinsue** [comment]
@vala Ok no problem, i have removed simple_form_extension gem for now. I only use selectize anyways, got it working now without problems. When I get home i'll check into this issue and try to PR a solution =)

**Comment by vala** [comment]
No problem @schinsue thanks for your input ;)
