### ISSUE TITLE
Error: ref.split is not a function (Slider)

### ISSUE THREAD

**Issue by iaa047** [glyph-fr/simple_form_extension#16]
Error: ref.split is not a function (Slider)
Variable ref is integer.
vendor/assets/javascripts/simple_form_extension/slider.coffee
Google Chrome (v48, v56)

**Comment by vala** [comment]
https://github.com/glyph-fr/simple_form_extension/blob/master/vendor/assets/javascripts/simple_form_extension/slider.coffee#L3

Should cast into `String` before calling split.
For now, try to force a string value in your input's `:value` argument.

**Comment by vala** [comment]
Fixed in f5a5a53 and released new 1.4.8 version, you can `bundle update --source simple_form_extension`
