### ISSUE TITLE
Cannot read property '0' of undefined (slider)

### ISSUE THREAD

**Issue by iaa047** [glyph-fr/simple_form_extension#17]
slider.coffee

value = (values = (ref = this.$el.data('slider-value')) != null ? ref.toString().split(',') : void 0) ? values.length <= 1 ? value[0] : (function() {  --------- **Uncaught TypeError: Cannot read property '0' of undefined**
        var j, len, results;
        results = [];
        for (j = 0, len = values.length; j < len; j++) {
          value = values[j];
          results.push(parseInt(value, 10));
        }
        return results;
      })() : void 0;

**Comment by vala** [comment]
PRs are welcome ;)

**Comment by iaa047** [comment]
Can you change one line of code? 
vendor/assets/javascripts/simple_form_extension/slider.coffee 
5 row
value[0]  -> values[0]

**Comment by vala** [comment]
Will do later, but you can do it and PR
