### ISSUE TITLE
undefined method `before_filter' for RedactorRails::DocumentsController:Class when deploying to AWS EC2

### ISSUE THREAD

**Issue by Adsidera** [glyph-fr/simple_form_extension#19]
```
/opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/redactor-rails-0.5.0/app/controller/redactor_rails/documents_controller.rb:2:in `<class:DocumentsController>': undefined method `before_filter' for RedactorRails::DocumentsController:Class (NoMethodError)
Did you mean?  before_action
	from /opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/gems/redactor-rails-0.5.0/app/controller/redactor_rails/documents_controller.rb:1:in `<top (required)>'
```

**Comment by Adsidera** [comment]
practically, EC2 doesnt like the `before_filter` lines in the `documents_controller.rb` and `pictures_controller.rb`
I could only fix the issue by monkeypatching the 2 files (replacing `before_filter` with `before_action`) in the ssh environment :(

**Comment by vala** [comment]
It's a Rails 5.1 issue, `before_filter` has been removed from ActionController. This has no link with EC2. We should fix this, but I can't give you any ETA on this.

**Comment by Adsidera** [comment]
Yes I agree, it is a Rails 5 issue not directly a EC2. Thank you for your awesome gem though!

**Comment by Adsidera** [comment]
Or maybe is there a way to choose which inputs? I mean if I want to use the simple_form extensions just for slider and selectize and I do not want to include par force redactor-rails, is there a way to opt this feature out?

**Comment by vala** [comment]
As of now there is no way of doing that, and I can't tell we'll provide this feature soon. Wouldn't you be able to submit a PR to switch between before_filter / before_action depending on Rails version ?

**Comment by vala** [comment]
As a workaround I used for some old gems too, you can monkey patch ActionController::Base.
Note that this is not optimal, but if you are not able to fix the gem, this seems to me an acceptable fix.

```ruby
# lib/before_filter_patch.rb
module BeforeFilterPatch
  extend ActiveSupport::Concern

  included do
    class << self
      alias_method :before_filter, :before_action
    end
  end
end

# config/initializers/application_controller_renderer.rb
require "before_filter_patch"

ActiveSupport::Reloader.to_prepare do
  ActionController::Base.send(:include, BeforeFilterPatch)
end
```

**Comment by Adsidera** [comment]
hi @vala thank you a lot, merci, also for your smart workaround! I will try my best to submit a PR as you advised me, and again, thanks!

**Comment by Adsidera** [comment]
(although, to be honest, the issue should be fixed by the guys maintaining the `redactor-rails` gem)

**Comment by Adsidera** [comment]
I think we could close this issue, as this can be solved by adding the small module suggested by @vala :)) Never had issue since then!

**Comment by swiknaba** [comment]
Just for the record and future researchers: This will never get fixed in `redactor-rails` because there is now `redactor2_rails` which fixes the mentioned error (they just closed the PR without merging). I guess you don't depend on `redactor2-rails` since that one is paid. So either monkey patch it yourself, or if you need only a few things, use HTML5 - it got easy nowadays.
