### ISSUE TITLE
Slider doesn't work without model 

### ISSUE THREAD

**Issue by MFProduction** [glyph-fr/simple_form_extension#20]
hi, I noticed that when using slider in a form without model i get `undefined method field' for nil:NilClass`
```
<%= simple_form_for :export_params, url: export_path do |f| %>
<%= f.input :field, as: :slider, min: 0, max: 10 %>
```
but it's working without slider:
```
<%= simple_form_for :export_params, url: export_path do |f| %>
<%= f.input :field, as: string %>
```

**Comment by vala** [comment]
Actually this way of using forms is not supported in simple_form_extension.
Since we have no need for it ATM and don't see the use case for us, I won't add support to it by myself.

If you wish to add support to it feel free to provide a pull request !
