### ISSUE TITLE
couldn't find file 'redactor-rails/redactor' with type 'text/css'

### ISSUE THREAD

**Issue by catfishuang** [glyph-fr/simple_form_extension#21]
couldn't find file 'redactor-rails/redactor' with type 'text/css'

what's wrong with it?

**Comment by vala** [comment]
I'm not sure to remember why this doesn't work out of the box, but if you add :

```ruby
gem "redactor-rails", github: "glyph-fr/redactor-rails"
```

to your Gemfile, it should work !
