### ISSUE TITLE
Image input failing

### ISSUE THREAD

**Issue by ileri** [glyph-fr/simple_form_extension#22]
Before using simple_form_extension, in a simple form, I'm using image input as:

```ruby
<%= f.input :image, label: 'Image' %>
```

After installing simple_form_extension, as you said in **README**, to use custom image component, need to **explicitly call** them, so I'm not using Paperclip, so i didn't changed anything in this part. 

But the formerly working code is not working anymore, it say: 

> undefined method `image_file_name' for #<Event:0x000055fff3bdf968>
Did you mean?  image_will_change!

When i disable gem, the code is working normally.

**Using Rails 5.1.5**

**Comment by vala** [comment]
I understand that if you don't use either Paperclip or ActiveStorage, the gem will not work properly. This is an unwanted behavior but feel free to propose a fix or reopen to issue to discuss it
