### ISSUE TITLE
Info: Slider

### ISSUE THREAD

**Issue by ACPK** [glyph-fr/simple_form_extension#3]
Can you provide a sample line in the readme on using the slider feature?

**Comment by vala** [comment]
We'll try to do it as soon as we can.

But here's how you can use the slider input :

```ruby
= form.input :field, as: :slider, min: 0, max: 10, step: 2
```

You can find all the available options in the input's source code here : https://github.com/glyph-fr/simple_form_extension/blob/master/lib/simple_form_extension/inputs/slider_input.rb

Basically, the slider input is a `:number` field which we apply the [Bootstrap Slider](https://github.com/seiyria/bootstrap-slider) plugin on, with some of its options available through the input's options.

**Comment by ACPK** [comment]
@vala Awesome, thank you!

**Comment by ACPK** [comment]
@vala Any suggestions on getting the slider to show up? I'm using the Bootstrap gem (other bootstrap js features work) and the label shows up for the slider but the slider is nowhere to be found.

**Comment by vala** [comment]
Did you add the javascript and css includes to your manifests as explained in the README ?

**Comment by ACPK** [comment]
Yes

**Comment by vala** [comment]
@ACPK I saw that you found a fix on your test app with a colleague. Can you please detail what you had to do so we can improve the workflow to avoid manual fixes in your app ?

Please note that I update the README with details on custom input types : https://github.com/glyph-fr/simple_form_extension#slider

It's not complete and could be enhanced, but allows for a simple overview of the fields
