### ISSUE TITLE
selectize, validate presence, not show errors

### ISSUE THREAD

**Issue by simonini** [glyph-fr/simple_form_extension#6]
Selectize options does not show error to the user if user put empty value (with validation presence server side). Possible?

my code

View
```
  = f.input :artist_id, as: :selectize, collection: Artist.order("name ASC").all, creatable: true, placeholder:'Scegli Artista', label: 'Artista', required: true, input_html: {data: {search_artist: true}}
```

Model
```
validates_presence_of :title, :artist
```

**Comment by vala** [comment]
Yes, you're validating `:artist` presence, while you have a `:artist_id` field.
This is true for any input in rails or simple form, independently from the selectize input.

But if you use `:artist` as the key : 

```ruby
= f.input :artist, as: :selectize, collection: Artist.order("name ASC").all, creatable: true, placeholder:'Scegli Artista', label: 'Artista', required: true, input_html: {data: {search_artist: true}}
```

The selectize input should use `name="artist_id"` for the underlying html tag, but display the error.

**Comment by simonini** [comment]
:+1:  Thanks!
