### ISSUE TITLE
Override simple_form_extension overrides?

### ISSUE THREAD

**Issue by rvwong** [glyph-fr/simple_form_extension#7]
I'm getting a strange error for the date field, with simple_form it worked fine as 3 select boxes.  With simple_form_extension installed, I'm getting a "can't modify frozen FixNum" error.  Is there a way to using
f.input :name, as: <something> to override the date picker to go back to the original one from simple_form?

**Comment by vala** [comment]
Hi @rvwong,

What's the issue that you want to solve :

1. The `can't modify frozen FixNum` error ?
2. Or you absolutely want to be able to use the original `simple_form` date input ?

For the first one, can you please give us a way to reproduce the error quickly (like a code sample that we can run) or the detail of the related model, database schema (schema.rb) and form ?. 

My first idea is that you're trying to use the field on an `integer` attribute and not a `date` one. Maybe look at that.

For the second question, this is currently not possible in `simple_form_extension` as it has never been useful to us before, but some kind of input overrides cherry picking mechanisme could be thought to let you choose which overrides you want to include with the gem.

**Comment by rvwong** [comment]
Thank you for getting back to me so quickly!  I'll try and see if I can find a way to get a code snippet to you.  As it is the offending line in my code is:
= upp.input :start_date, :order => [:year, :month, :day], :label => t('user_properties_plan.start_date')
as you can see nothing really weird, also this line of code works perfectly with simple_form, the only thing I can say is that :start_date is a Date object not a DateTime object, not sure if that is relevant

**Comment by vala** [comment]
Hi @rvwong, can you please provide as much data as you can to help us reproduce your issue ? I just tried to reproduce it with a date field but everything works fine here : the `Date` object works as expected, with a simple date picker, without the time picker. 

Please give us the stack trace of your error, and more context of your application : controller, schema, model, complete view.

Also, note that the `:order => [...]` option does not affect the date picker.

**Comment by rvwong** [comment]
Thank you, I will as soon as there is some time. For now I forked your repo, and I commented out the autoload to load your date picker override.  The error went away, so there is something about my rails environment that is not agreeing with your override code.  The upp.input is part of a nested resource, have you tested it in a nested form?

**Comment by vala** [comment]
I did not test it in a nested form, but this should not be an issue AFAIK. 
But I'll wait for you to provide me with more test data before continuing my investigations.

**Comment by vala** [comment]
Closing this issue since it is inactive for almost 1 year
